"""add image_url to User

Revision ID: 48567f3faf
Revises: 316bb58e84f
Create Date: 2015-03-11 01:58:56.293996

"""

# revision identifiers, used by Alembic.
revision = '48567f3faf'
down_revision = '316bb58e84f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    ### end Alembic commands ###
