"""create productions table

Revision ID: 5a17d6dc829
Revises: 4f8040bc18a
Create Date: 2015-03-09 21:15:40.948068

"""

# revision identifiers, used by Alembic.
revision = '5a17d6dc829'
down_revision = '4f8040bc18a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_production_name', 'productions', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_production_name', table_name='productions')
    op.drop_table('productions')
    ### end Alembic commands ###
